language: python
python:
  - "3.7"

services:
  - docker

before_insta:
  - docker-compose up -d
  - docker ps

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"